### PR TITLE
GIF export

### PR DESCRIPTION
**Pull request by jhoon-cho**
## Summary
export traffic simulation screen to gif

## Detail
- move `assets/` to `example/assets/`
- change the example commands in README accordingly
- add `pillow==10.4.0` to `environment.yml`
- add `plot_gif` option for exporting gif
- add simulation example to README

### CODE REVIEW

**Comment by cathywu** [comment]
Thanks for the PR! @jhoon-cho is the expected behavior that the user runs the entire simulation? How long should this take? Is it possible to only render and save the gif on the last simulation? I think right now, all 15 simulations are being rendered, which takes some time (minutes).

**Comment by jhoon-cho** [comment]
@cathywu At the current stage, I hard-coded to record only second to the last simulation since the last simulation has only one vehicle running under the given random seed. It may depend on the screen size, but it takes less than 10 secs for my 14-inch MacBook pro.

**Comment by cathywu** [comment]
Hm, when I run `$ python example/simulator.py --run-idm --plot-gif`, I get multiple simulation runs... should I expect only one?
```
pygame 2.6.0 (SDL 2.28.4, Python 3.8.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO:root:Arugments {'run_idm': True, 'run_custom': False, 'no_render': False, 'plot_gif': True}
INFO:root:Starting the simulator...
INFO:root:Created info_object...
INFO:root:Set screen_width...
INFO:root:Created Environment Object...
INFO:root:Running IDM Simulation No.  1 with 11 vehicles and road length of  41 meters.
INFO:root:Running IDM Simulation No.  2 with  2 vehicles and road length of  27 meters.
INFO:root:Running IDM Simulation No.  3 with 80 vehicles and road length of 145 meters.
INFO:root:End of the simulation...
```

**Comment by jhoon-cho** [comment]
`plot-gif` option includes all 15 simulation runs to have fundamental diagrams with multiple points. Only at the 14th run does it capture the screen to plot a gif video.

**Comment by cathywu** [comment]
Then, how does your run complete in 10 seconds if you need to render the first 14 simulations first? I don't want to wait that long!

**Comment by jhoon-cho** [comment]
@cathywu The recent commit (`0b40ffcf8942cb0451767e25cd78ec4a80488e07`) is for rendering only at 14th simulation.

**Pull request merged**
